---
site_name: BUVIS
site_description: Bob's Universal and Very Intelligent System
site_author: Tomáš Bouška
site_url: https://docs.buvis.net

repo_name: buvis/docs
repo_url: https://github.com/buvis/docs
edit_uri: "edit/main/docs/"

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  language: en
  features:
  - navigation.sections
  - navigation.tracking
  - search.share
  - search.suggest
  palette:
  - scheme: default
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/lightbulb-outline
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: indigo
    toggle:
      icon: material/lightbulb
      name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

docs_dir: ../../src

# Plugins
plugins:
# https://squidfunk.github.io/mkdocs-material/setup/setting-up-site-search/#built-in-search
- search
# https://squidfunk.github.io/mkdocs-material/setup/adding-a-git-repository/#revision-date-localized
- git-revision-date-localized
- minify:
    minify_html: true

# Customization
extra:
  social:
  - icon: fontawesome/brands/github
    link: https://github.com/tbouska

copyright: Copyright &copy; 2022 Tomáš Bouška

# https://www.mkdocs.org/user-guide/configuration/#markdown_extensions
markdown_extensions:
- admonition
- meta
- codehilite:
    noclasses: "True"
    pygments_style: tango
- toc:
    permalink: true
- pymdownx.superfences

# Page tree
nav:
- Overview: index.md
- Installation: installation.md
- Operations: operations.md
- Namespaces:
  - flux-system: namespaces/flux-system.md
  - gtd: namespaces/gtd.md
  - hajimari: namespaces/hajimari.md
  - kube-system: namespaces/kube-system.md
  - longhorn-system: namespaces/longhorn-system.md
  - media: namespaces/media.md
  - minio-operator: namespaces/minio-operator.md
  - monitoring: namespaces/monitoring.md
  - network: namespaces/network.md
  - openfaas: namespaces/openfaas.md
  - smarthome: namespaces/smarthome.md
  - system-upgrade: namespaces/system-upgrade.md
  - vpn: namespaces/vpn.md
- Catalogue: catalogue/index.md
